export const properties = [
  {
    id: 1,
    imageUrl: 'assets/anonchat-call.png',
    link: 'https://anonymous.roromomo.com/',
    githubLink: 'https://github.com/Jatin917/anonchat',
    techStack: [
      'HTML',
      'CSS',
      'Javascript',
      'SocketIO',
      'WebRTC',
      'Redis',
      'Langchain',
      'Transformer'
    ],
    title: 'AnonChatCall',
    Status: 'Completed',
    description: `AnonConnect is a real-time anonymous chat and voice calling platform built using Node.js, Socket.IO, WebRTC, and Redis. It supports 500+ daily active users with instant matchmaking and low-latency communication. The platform was deployed on Ubuntu Linux with Dockerized Redis, and includes heartbeat-based session management, ICE restarts, and robust cleanup logic to ensure stability and reliability under high user churn.`,
  },
  {
    id: 2,
    imageUrl: 'assets/erp.png',
    link: 'https://erpp-frontend.netlify.app/workbench',
    githubLink: 'https://github.com/jatin917/erp',
    techStack: [
      'pSQL',
      'Express.js',
      'React.js',
      'Node.js',
      'Redis',
      'Hostinger',
      'Linux',
      'Docker',
      'BullMQ',
      'Typescript'
    ],
    title: 'ERP',
    Status: 'Completed',
    description: `Developing a multi-tenant SaaS School ERP using Node.js, Prisma, and React with comprehensive modules for attendance, admissions, fees, exams, communication, and role-based access management, serving 500+ students. Built an automated timetable and attendance system with conflict-free lecture scheduling using Prisma transactions, effective-date updates, and strict prevention of double-booked teachers across 200+ academic working days, reducing manual administrative workload by 40%.`,
  },
  {
    id: 3,
    imageUrl: 'assets/himraahi.png',
    link: 'https://live.himraahi.in/',
    githubLink: 'https://live.himraahi.in/',
    techStack: [
      'MongoDB',
      'Express.js',
      'React.js',
      'Node.js',
      'Firebase',
      'Cloudinary',
      'SocketIO',
      'Google Analytics'
    ],
    title: 'Himraahi',
    Status: 'Completed',
    description: `Himraahi is a Uttarakhand-based mobility startup that enables users to track buses and book tickets through a unified digital platform. Instead of operating its own fleet, Himraahi collaborates with private local bus operators, allowing them to register on the platform and list their services. The platform brings customers to these operators while providing passengers with real-time bus tracking, route visibility, and seamless ticket booking across the region.`,
  },
  {
    id: 5,
    imageUrl: 'assets/flimpireLg.png',
    link: 'https://jattusflimpire.netlify.app/',
    githubLink: 'https://github.com/Jatin917/flimpire',
    techStack: ["ReactJS", "Redux Toolkit", "Firebase"],
    title: "Flimpire",
    Status: "Completed",
    description:
      "Developed a responsive, user-focused frontend using React.js, leveraging Redux Toolkit for modular state management. The backend is supported by Firebase, providing user authentication and real-time database management. Key features include video playback with React Video Library, dynamic rendering of movie thumbnails, titles, and details, along with search and recommendation functionalities, offering users an engaging content discovery experience.",
  },
  {
    id: 8,
    imageUrl: 'assets/stackoverflow.png',
    link: 'https://nullstackoverflow.netlify.app/',
    githubLink: 'https://github.com/Jatin917/nullclasstasks',
    techStack: ["MERN Stack", "JWT Token", "react redux", "React Router", "firebase", "multer", "nodemailer", "p-queue"],
    title: "StackOverFlow Clone",
    Status: "Completed",
    description:
      "This platform offers Google and phone authentication for seamless access. Users can engage in a public space by sharing pictures, videos, and comments, with posting limits based on their friend count. Multi-language support (Spanish, Hindi, Portuguese, Chinese, French, English) ensures global accessibility, with OTP verification for secure language switching. A dedicated Q&A section allows users to ask and answer questions with titles, descriptions, and tags, fostering community interaction and knowledge sharing.",
  },
];
